FROM php:7.4-apache

# Install necessary dependencies
# Copy your web files to the appropriate directory
COPY site/ /var/www/html/

# Install PDO and PDO PostgreSQL extension
RUN docker-php-ext-install pdo pdo_mysql

# Expose port 80
EXPOSE 80