/* 1a */
CREATE OR REPLACE TYPE DIRECCION1 AS OBJECT (
    CALLE VARCHAR2(40),
    CIUDAD VARCHAR(40),
    CP NUMBER(5)
);
/
DROP TYPE DIRECCION1 FORCE;

CREATE OR REPLACE TYPE PERSONA AS OBJECT(
    CODIGO NUMBER(5),
    NOMBRE VARCHAR2(40),
    DIREC DIRECCION1,
    FECHA_NAC DATE
);
/
DROP TYPE PERSONA FORCE;

DECLARE
    DIR DIRECCION1 := DIRECCION1(NULL,NULL,NULL);
    P PERSONA := PERSONA(NULL,NULL,NULL,NULL);
BEGIN
    DIR.CALLE := 'LA MINA';
    DIR.CIUDAD := 'GUADALAJARA';
    DIR.CP := '19001';
    P.CODIGO := 1;
    P.NOMBRE := 'JUAN';
    P.DIREC := DIR;
    P.FECHA_NAC := '10/NOV/1988';
END;
    /
ROLLBACK;

INSERT INTO ALUMNOS VALUES(1,'ALUMNO1',DIRECCION1('CALLE1','CIUDAD1',28026),'06/DEC/2001');
INSERT INTO ALUMNOS VALUES(1,'ALUMNO2',DIRECCION1('CALLE2','CIUDAD2',28022),'17/DEC/2001');
SELECT * FROM ALUMNOS;
SELECT * FROM ALUMNOS C WHERE DIREC.CIUDAD='GUADALAJARA';
SELECT CODIGO.DIREC FROM ALUMNOS;
UPDATE ALUMNOS C SET C.DIREC.CIUDAD='guadalajara' WHERE C.DIREC.CIUDAD='GUADALAJARA';
DECLARE
    CURSOR C1 IS SELECT NOMBRE,C.DIREC.CIUDAD FROM ALUMNOS C;
    V_NOMBRE VARCHAR2(20);
    V_CALLE VARCHAR2(20);
BEGIN
    OPEN C1;
    FETCH C1 INTO V_NOMBRE,V_CALLE;
    WHILE C1%FOUND LOOP
        DBMS_OUTPUT.PUT_LINE('ALUMNO; ' || V_NOMBRE || ' - CALLE: ' || V_CALLE);
        FETCH C1 INTO V_NOMBRE,V_CALLE;
    END LOOP;
END;
DELETE FROM ALUMNOS C WHERE C.DIREC.CIUDAD="guadalajara";
select * from ALUMNOS;
ROLLBACK;