CREATE OR REPLACE TYPE VETERINARIO AS OBJECT(
    ID INTEGER,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(200)
);
/

CREATE OR REPLACE TYPE MASCOTA AS OBJECT(
    ID INTEGER,
    RAZA VARCHAR2(100),
    NOMBRE VARCHAR2(100),
    VET REF VETERINARIO
);
/

DROP TABLE MASCOTAS;
DROP TABLE VETERINARIOS;
CREATE TABLE VETERINARIOS OF VETERINARIO;
INSERT INTO VETERINARIOS VALUES (1,'EDUARDO','CALLE LA CALLE');
CREATE TABLE MASCOTAS OF MASCOTA;
INSERT INTO MASCOTAS VALUES(1,'PERRO','SANXE',(SELECT REV(V)FROM VETERINARIOS V WHERE V.ID=1));
SELECT * FROM MASCOTAS;
SELECT ID, NOMBRE, DEREF(VET) FROM MASCOTAS;
SELECT NOMBRE,RAZA,DEREF(M.VET).NOMBRE FROM MASCOTAS M;
DROP TABLE MASCOTAS;
DROP TABLE VETERINARIOS;
DROP TYPE MASCOTAS;
DROP TYPE VETERINARI;