DROP TYPE TIPO_CUBO;
CREATE TYPE TIPO_CUBO AS OBJECT (
    LARGO INTEGER,
    ANCHO INTEGER,
    ALTO INTEGER,
    MEMBER FUNCTION SUPERFICIE RETURN INTEGER,
    MEMBER FUNCTION VOLUMEN RETURN INTEGER,
    MEMBER PROCEDURE MOSTRAR
);
/
--METODO
CREATE TYPE BODY TIPO_CUBO INTEGER,
MEMBER FUNCTION SUPERFICIE RETURN INTEGER IS
BEGIN
    RETURN 2*(LARGO*ANCHO+LARGO*ALTO+ANCHO*ALTO);
END;
--OJO
MEMBER FUNCTION VOLUMEN RETURN INTEGER IS
BEGIN
    RETURN LARGO*ANCHO*ALTO;
END;
MEMBER PROCEDURE MOSTRAR IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('LARGO: ' || '- ' || LARGO || ' ANCHO: ' ||ANCHO|| ' - ALTO: ' || ALTO);
    DBMS_OUTPUT.PUT_LINE('VOLUMEN: ' || VOLUMEN || ' SUPERFICIE ' || SUPERFICIE);
END;