/**/
DROP TYPE LISTIN AS OBJECT;
DROP TYPE TELEFONO FORCE;
DROP TABLE CLIENTS;
/*Se crea el tipo telefono como objeto con los atributos tipo y numero*/
CREATE OR REPLACE TYPE TELEFONO AS OBJECT(
    TIPO( VARCHAR(25)
    NUMERO NUMBER
);
/
/*Se crea el tipo listin como una tabla del tipo telefono*/
CREATE OR REPLACE TYPE LISTIN IS TABLE OF TELEFONO;
/
/*sE CREA LA TABLA CLIENTS*/
CREATE TABLE CLIENTS(
    ID_CLIENTE NUMBER,
    NOMBRE VARCHAR(25),
    APELLIDO VARCHAR(25),
    DIRECCION VARCHAR(30),
    POBLACION VARCHAR(30),
    PROVINCIA VARCHAR(30),
    TELEFONO LISTIN
)
NESTED TABLE TELEFONO STORE AS TEL_TB;
/*INSERCIONES EN LA TABLA CLIENTS*/
INSERT INTO CLIENTS VALUES(10,'ABDUL','MASHALA','C/ ANTONIO LOPEZ 246','MADRID','MADRID',LISTIN(TELEFONO('FIJO,',123456789),TELEFONO('MOVIL',632199366),TELEFONO('MOVIL',632199377)));
INSERT INTO CLIENTS VALUES(20,'EDUARDO','PIEDELOBO','C/ INVENTADA 1','ALBACETE','CASTILLA-LA MANCHA',LISTIN(TELEFFONO('FIJO',123456987),TELEFONO('MOVIL',632199854),TELEFONO('MOVIL',651170793)));
INSERT INTO CLIENTS VALUES(30,'GIGALITH','TYPHOLSION','C/ DONDE ESTA LA CALLE 2','ESPIRITO SANTO','VITORIA',LISTIN(TELEFONO('FIJO',33102758),TELEFONO('MOVIL',65165199),TELEFONO('MOVIL',65168975)));
/*SE MUESTRAN TODOS LOS REGISTROS DE LA TABLA CLIENTS*/
SELECT * FROM CLIENTS;
 SELECT A.ID_CLIENTE,CONCAT(A.NOMBRE,(CONCAT(' ', A.APELLIDO))) NOMBRE_COMPLETO,A.DIRECCION, CONCAT(A.PROVINCIA,(CONCAT(' ',A.POBLACION))) PROVINCIA_POBLACION,
 T.* FROM CLIENTS A, TABLE (A.TELEFONO) T;

SELECT * FROM USER_OBJECTS;

SELECT * FROM all_objects 
where OWNER= 'javier';

SELECT * FROM all_objects 
where OWNER= 'javier' and OBJECT_TYPE='TYPE';

SELECT * FROM ALL_OBJECTS;

SELECT * FROM USER_NESTED_TABLES 
WHERE TABLE_TYPE_OWNER='javier';

SELECT * FROM ALL_NESTED_TABLES 
WHERE TABLE_TYPE_OWNER='javier';

SELECT A.ID_CLIENTE, T.* FROM CLIENTS A, TABLE (A.TELEFONO) T WHERE A.ID_CLIENTE=3;

/*SE ACTUALIZA DE LA TABLA CLIENTS EL REGISTRO CORRESPONDIENTE AL CLIENTE CON ID 1*/
UPDATE CLIENTS SET TELEFONO = LISTIN(TELEFONO('FIJO',999999999), TELEFONO ('MOVIL_PERSONAL', 666666666), TELEFONO('MOVIL_EMPRESA',655555555))
WHERE ID_CLIENTE = 1;
SELECT A.ID_CLIENTE T.* FROM CLIENTS A, TABLE (A.TELEFONO) T);
SELECT A.ID_CLIENTE, A.nombre, A.tipo, A.numero FROM CLIENTS A,TABLE (A.TELEFONO) T;



