CLEAR SCR;




CREATE TYPE TIPO_ADDRESS AS OBJECT (
DIR VARCHAR(100),
CP NUMBER(5)
);
/

CREATE TYPE TIPO_CONTACTO AS OBJECT (
TELEFONO NUMBER,
EMAIL VARCHAR(100)
);
/

CREATE TYPE TIPO_PERSON AS OBJECT(
ID VARCHAR(20),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(30),
DIRECCION TIPO_ADDRESS,
CONTACTO TIPO_CONTACTO)
NOT FINAL
/

CREATE TYPE TIPO_CUSTOMER UNDER TIPO_PERSON 
(N_PEDIDOS NUMBER)
/

DESC TIPO_ADDRESS;

CREATE OR REPLACE TYPE TIPO_ARTICULO AS OBJECT (
IDART NUMBER,
NOMBRE VARCHAR(30),
DESCRIPCION VARCHAR(100),
PRECIO NUMBER,
PORCT_IVA NUMBER
);
/

CREATE TYPE TABLA_ARTICULOS AS TABLE OF TIPO_ARTICULO;
/

CREATE OR REPLACE TYPE TIPO_LISTA_DETALLE AS OBJECT (
NUMERO NUMBER,
ARTICULO TIPO_ARTICULO,
CANTIDAD NUMBER
)
/

CREATE TYPE TAB_LISTA_DETALLE AS TABLE OF TIPO_LISTA_DETALLE;
/

CREATE TYPE TIPO_LISTA_COMPRA AS OBJECT(
ID NUMBER,
FECHA DATE,
CLI REF TIPO_CUSTOMER,
DETALLE TAB_LISTA_DETALLE,
MEMBER FUNCTION TOTAL RETURN NUMBER
)
/
CREATE TYPE BODY TIPO_LISTA_COMPRA AS
MEMBER FUNCTION TOTAL RETURN NUMBER IS
	I INTEGER;
	TOT NUMBER:=0;
BEGIN
	FOR I IN 1..DETALLE.COUNT LOOP
		TOT:=TOT + (DETALLE(I).CANTIDAD *
		DETALLE(I).ARTICULO.PRECIO)*
		(1+(DETALLE(I).ARTICULO.PORCT_IVA/100));
	END LOOP;
	RETURN TOT;
	END;
END;
/

DROP TABLE CUSTOMERS;

CREATE TABLE CUSTOMERS OF TIPO_CUSTOMER;

INSERT INTO CUSTOMERS VALUES (1,'PEDRO','SUAREZ',TIPO_ADDRESS('PASEO DEL MUSEO, 15',28009),
						   TIPO_CONTACTO(938383838,'PSUAREZ@ONO.ES'),0);

INSERT INTO CUSTOMERS VALUES (2,'JUANA','GOMEZ',TIPO_ADDRESS('GRAN VIA, 15',28885),
						   TIPO_CONTACTO(938888888,'JGOMEZ@ONO.ES'),0);
DROP TABLE LISTAS_DE_COMPRAS;

CREATE TABLE LISTAS_DE_COMPRAS OF TIPO_LISTA_COMPRA
	NESTED TABLE DETALLE STORE AS TDETALLE;

--SELECT ATACA A LA TABLA LISTA COMPRA
INSERT INTO LISTAS_DE_COMPRAS SELECT 1, CURRENT_DATE, REF(C), TAB_LISTA_DETALLE(TIPO_LISTA_DETALLE(
				      1, TIPO_ARTICULO(1,'BARRA DE PAN','TIPO BAGUETTE',1,7),4),
				      TIPO_LISTA_DETALLE(2,TIPO_ARTICULO(2,'LONCHAS DE JAMON','TIPO DE 						IBERICO',6,7),4)) FROM CUSTOMERS C WHERE C.ID=1;

SELECT * FROM LISTAS_DE_COMPRAS;

SELECT ID, FECHA, DEREF(CLI), DETALLE FROM LISTAS_DE_COMPRAS;

SELECT ID, C.TOTAL() FROM LISTAS_DE_COMPRAS C;